steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'image-transformer',
      '--source', 'cloud-functions/image-transformer/src/',
      '--runtime', 'python39',
      '--entry-point', 'main',
      '--trigger-bucket', '${_TRIGGER_BUCKET}',
      '--set-env-vars', 'DESTINATION_BUCKET=${_DESTINATION_BUCKET}'
    ]