runtime: python39
env: standard

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  SECRET_KEY_RESOURCE_ID: ${SECRET_KEY_RESOURCE_ID}
  IMAGES_BUCKET_NAME: ${IMAGES_BUCKET_NAME}
  OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}